### PR TITLE
Log before retrieving the ACL

### PR DESCRIPTION
**Pull request by morwoen**
This has caught our team a little. We had to investigate the code to find what exactly was giving us the 403. Also there is no logging in case everything is identical and the GetObjectAcl fails which was the permission we were missing.

Hopefully the list in the readme should help people in the future.

Please let me know if I have missed a permission or I got something wrong.

Thanks.

### CODE REVIEW

**Comment by tboerger** [comment]
We aren't using the readme for documentation, please raise a pull request to https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-s3-sync/index.md.

**Comment by morwoen** [comment]
Thanks for the info @tboerger . I've created a PR there https://github.com/drone/drone-plugin-index/pull/189

Do you think it is unnecessary to be in the README here as well? Do you agree with the additional logging I've added as part of this PR? If you are happy with the logging but not the README change let me know so I can revert it.

Thanks

**Comment by tboerger** [comment]
I would prefer to drop the README change.

**Comment by morwoen** [comment]
Done :) probably best to squash the PR so it is nice and tidy 👍

**Review by tboerger — APPROVED** [review]

**Review by tphoney — APPROVED** [review]

**Comment by tphoney** [comment]
Thanks for the PR @morwoen  !!

**Pull request merged**
