### PR TITLE
fix issue #17, NoSuchKey

### PR DESCRIPTION
**Pull request by m00k**
For configurations where syncing is enabled and there is a target defined, e.g.
````yml
source: dist
target: foo/bar/
delete: true
````
the remote path [returned from S3](https://github.com/drone-plugins/drone-s3-sync/blob/master/aws.go#L339) needs to be stripped of the target portion before being compared with the local path.

### CODE REVIEW

**Review by tboerger — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by tboerger** [comment]
@bradrydzewski does this also look right to you?

**Comment by bradrydzewski** [comment]
unfortunately I do not have enough experience with this plugin to answer that question, and my bandwidth is quite low right now. I wonder if we can find a maintainer for this plugin that can devote a little more time to it? previously it was nlf that took care of this plugin.

**Comment by bradrydzewski** [comment]
I can say that in `plugins/s3` we added a `strip_prefix` parameter to strip the prefix from the target. Perhaps this solution should be mirrored in this plugin?

https://github.com/drone-plugins/drone-s3/blob/master/main.go#L69

**Comment by tboerger** [comment]
So far it seems to be fine, so I'm going to merge it.

**Pull request merged**
