### PR TITLE
Apply streamline PR

### PR DESCRIPTION
**Pull request by tboerger**
@nlf same as for the other already migrated plugins.

### CODE REVIEW

**Comment by nlf** [comment]
I have no idea why you created a whole new pull request from scratch, duplicating all the work I already did. If something was missing, update the other pr

**Comment by tboerger** [comment]
Because I realized afterwards that your PR have been pushed to this repo, and beside that it's not nice to fiddle aroubd in a PR from somebody else without his confirmation :)

**Comment by tboerger** [comment]
And my PR is done against your PR because it relies on it.

**Comment by bradrydzewski** [comment]
if this PR is based on the original, we should be able to merge the original right? Probably cleaner to do so, so I'll get that merged now

**Comment by nlf** [comment]
that's what i get for checking on things via mobile :grimacing: these changes all look fine to me

**Comment by tboerger** [comment]
Than I think i have to create a PR for master :)

**Comment by kzaitsev** [comment]
LGTM

**Comment by tboerger** [comment]
Replaced with #23

**Pull request closed without merging**
