### PR TITLE
Adding support for uploading files with Content Encoding

### PR DESCRIPTION
**Pull request by divercraig**
Second attempt at a pull request to implement the feature requested in issue #13

### CODE REVIEW

**Comment by inquire** [comment]
Super awesome stuff. I've been looking for something like this for some projects. Is there an ETA when this will be merged in?

**Comment by nlf** [comment]
much better, LGTM

**Comment by bradrydzewski** [comment]
@divercraig can you add documentation for the new `content_encoding` field to the `DOCS.md` file? thanks!

**Comment by divercraig** [comment]
@bradrydzewski I've updated the documentation.

**Comment by tboerger** [comment]
LGTM

**Comment by divercraig** [comment]
Thanks Guys, when can we merge it?

**Comment by nlf** [comment]
how about now?

**Pull request merged**
