### PR TITLE
Update AWS SDK

### LINKED ISSUE #32: 501 during upload
I get

> NotImplemented: A header you provided implies functionality that is not implemented - ERROR 501

whenever I try to upload something. Apparently this is a known issue affecting SDK versions 1.6.2 and earlier.

See: https://github.com/aws/aws-sdk-go/issues/1379

### PR DESCRIPTION
**Pull request by gabro**
Ok, here's my attempt to fix #32 

Disclaimer: I'm an absolute rookie with go.

I've managed to setup go and install govendor, then I ran:

```
govendor fetch github.com/aws/aws-sdk-go/aws
govendor fetch github.com/aws/aws-sdk-go/aws/awserr
govendor fetch github.com/aws/aws-sdk-go/aws/awsutil
govendor fetch github.com/aws/aws-sdk-go/aws/client
govendor fetch github.com/aws/aws-sdk-go/aws/client/metadata
govendor fetch github.com/aws/aws-sdk-go/aws/corehandlers
govendor fetch github.com/aws/aws-sdk-go/aws/credentials
govendor fetch github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
govendor fetch github.com/aws/aws-sdk-go/aws/credentials/stscreds
govendor fetch github.com/aws/aws-sdk-go/aws/defaults
govendor fetch github.com/aws/aws-sdk-go/aws/ec2metadata
govendor fetch github.com/aws/aws-sdk-go/aws/endpoints
govendor fetch github.com/aws/aws-sdk-go/aws/request
govendor fetch github.com/aws/aws-sdk-go/aws/session
govendor fetch github.com/aws/aws-sdk-go/aws/signer/v4
govendor fetch github.com/aws/aws-sdk-go/internal/shareddefaults
govendor fetch github.com/aws/aws-sdk-go/private/endpoints
govendor fetch github.com/aws/aws-sdk-go/private/protocol
govendor fetch github.com/aws/aws-sdk-go/private/protocol/query
govendor fetch github.com/aws/aws-sdk-go/private/protocol/query/queryutil
govendor fetch github.com/aws/aws-sdk-go/private/protocol/rest
govendor fetch github.com/aws/aws-sdk-go/private/protocol/restxml
govendor fetch github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
govendor fetch github.com/aws/aws-sdk-go/private/signer/v4
govendor fetch github.com/aws/aws-sdk-go/private/waiter
govendor fetch github.com/aws/aws-sdk-go/service/cloudfront
govendor fetch github.com/aws/aws-sdk-go/service/s3
govendor fetch github.com/aws/aws-sdk-go/service/sts
```

Hopefully that did the trick...

### CODE REVIEW

**Comment by gabro** [comment]
Apparently it didn't... any guidance on go dependency management would be greatly appreciated!

**Comment by bradrydzewski** [comment]
@tboerger I think, for security reasons, only maintainers should perform large vendor updates until we have a process in place to validate dependency authenticity. This is planned in the official Go dep tool (see https://github.com/golang/dep/issues/121) but is not yet available.

**Comment by tboerger** [comment]
> @tboerger I think, for security reasons, only maintainers should perform large vendor updates until we have a process in place to validate dependency authenticity. This is planned in the official Go dep tool (see golang/dep#121) but is not yet available.

Yeah maybe you are right. I will prepare another PR to update it. Sorry for the noise @gabro

**Comment by tboerger** [comment]
Providing the update via https://github.com/drone-plugins/drone-s3-sync/pull/34

**Comment by gabro** [comment]
@tboerger no problem, thanks for the update :)

**Pull request closed without merging**
