### PR TITLE
Add MFA Auth

### PR DESCRIPTION
**Pull request by arhont375**
This MR adds possibility to work with AWS MF authorization.

Plugin will start MFA authorization if MfaKey and MfaSerial is provided in addition to Key and Secret.

### CODE REVIEW

**Comment by tboerger** [comment]
Looks good code-wise, but since I'm not an AWS user I don't know if that makes sense.

**Comment by arhont375** [comment]
@tboerger  Thank you for code review!
Is there someone who can review/test this AWS functionality if I will resolve conflicts? 
As I want to prepare similar PR for `docker` plugin, someone with AWS experience will also need to check that.

**Comment by bradrydzewski** [comment]
how does MFA work in this case? Does it block the CI pipeline and wait for someone to manually authorize token generation?

**Comment by arhont375** [comment]
No. Is it even possible to implement with Drone?

When you creating MFA device in AWS it provides you MfaKey that will be used to init OTP manager on your device or whatever that it will be possible to generate temporary tokens. In case if you have access to this token you can supply it to this plugin and supply your MFA device ARN (arn:aws:...:mfa/email). Based on provided MfaKey and current time temporary token will be generated and used to authenticate in AWS on your behalf.

**Pull request closed without merging**
