### PR TITLE
Cloudfront

### LINKED ISSUE #10: Add support for invalidating cloudfront
I am working on a PR for this right now, this is just to keep tracking of effort.

Feedback is welcome on the changes on my cloudfront branch.

### PR DESCRIPTION
**Pull request by ericanderson**
Fixes #10

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@nlf do you mind taking a look?

**Comment by nlf** [comment]
i'll check it in an hour or so :)

**Comment by nlf** [comment]
apparently "an hour or so" meant tomorrow, sorry about that.

LGTM

**Comment by jackspirou** [comment]
LGTM

**Comment by jackspirou** [comment]
I think everything is good functionally, but this is the first time I am seeing something like:

``` Go
a := newApp()
if err := a.loadVargs(); err != nil {...}
if err := a.sanitizeInputs(); err != nil {...}
```

I don't think this is a common pattern in the other plugins.

**Comment by nlf** [comment]
it's not a common pattern in other plugins, no. but it does enhance testability so i wasn't going to object to it. we don't have a plugin style guide currently (that i'm aware of) so i was going off the idea "if it's still readable, it's good enough"

**Comment by jackspirou** [comment]
@nlf I think that is fair and valid, I just wanted to mention it.  And I think a style guide would be great for plugins, just as long as we don't **completely** stop progress for the sake of style (like you inferred above).  

On that note I will merge :)

**Pull request merged**
